M48
; DRILL file {KiCad (6.0.4)} date Wed Jul 27 17:53:23 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-27T17:53:23+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.302
%
G90
G05
T1
X108.87Y-21.43
X114.65Y-21.43
T2
X124.575Y-87.645
X129.425Y-87.645
T3
X124.275Y-90.675
X129.725Y-90.675
T4
X136.969Y-34.29
T0
M30
