M48
; DRILL file {KiCad (6.0.4)} date Wed Mar 30 18:52:39 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-30T18:52:39+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
%
G90
G05
T1
X108.87Y-21.43
X114.65Y-21.43
T2
X124.575Y-87.645
X129.425Y-87.645
T3
X124.275Y-90.675
X129.725Y-90.675
T0
M30
